#!/usr/bin/env bash
# balancer install
sudo apt-get -y update
sudo apt-get install -y haproxy
echo "
frontend oscar
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    server 1267-lb-01 44.192.30.227 check
    server 1267-web-02 3.239.115.239  check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
