#!/usr/bin/env bash
# gives you information about the holbertonschool file

FILE="holbertonschool"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
        if [ -s "$FILE" ]; then
	   echo "School file is not empty"
	       else
		echo "School file is empty"
		    fi
		        if [ -f "$FILE" ]; then
			   echo "School is a regular file"
			       fi
			       else
			           echo "School file does not exist"
				   fi